// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hjYoVeU4u7dn5mbGaHoFnDJNBcLMNdU',
    appId: '1:79226297827:web:22b57148534b9dc95b54d6',
    messagingSenderId: '79226297827',
    projectId: 'flutter-projects-e2c13',
    authDomain: 'flutter-projects-e2c13.firebaseapp.com',
    storageBucket: 'flutter-projects-e2c13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDi7hxMIheMCBSSyrzqA2s2dhSxD2tA8',
    appId: '1:79226297827:android:d05ff343e5b10ec95b54d6',
    messagingSenderId: '79226297827',
    projectId: 'flutter-projects-e2c13',
    storageBucket: 'flutter-projects-e2c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0z1vTH2m-cOsrHw3ByhL1mwGv26S_RF0',
    appId: '1:79226297827:ios:f024a231907abf4f5b54d6',
    messagingSenderId: '79226297827',
    projectId: 'flutter-projects-e2c13',
    storageBucket: 'flutter-projects-e2c13.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0z1vTH2m-cOsrHw3ByhL1mwGv26S_RF0',
    appId: '1:79226297827:ios:f024a231907abf4f5b54d6',
    messagingSenderId: '79226297827',
    projectId: 'flutter-projects-e2c13',
    storageBucket: 'flutter-projects-e2c13.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8hjYoVeU4u7dn5mbGaHoFnDJNBcLMNdU',
    appId: '1:79226297827:web:c33b611d0c18e8435b54d6',
    messagingSenderId: '79226297827',
    projectId: 'flutter-projects-e2c13',
    authDomain: 'flutter-projects-e2c13.firebaseapp.com',
    storageBucket: 'flutter-projects-e2c13.firebasestorage.app',
  );
}
