name: app_cseiio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_do: ^4.1.1
  bytes_image_viewer: ^0.0.4
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  formz: ^0.8.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  latlong2: ^0.9.1
  mobile_scanner: ^7.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  syncfusion_flutter_calendar: ^28.2.11
  tinycolor2: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo_cseiio.png
